[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = deep+
board_build.filesystem = littlefs
lib_deps =
        GyverLibs/GyverDB@^1.4.2
        GyverLibs/Settings@^1.0
        knolleary/pubsubclient@^2.8
        iakop/LiquidCrystal_I2C_ESP32@^1.1.6
        ;GyverLibs/GyverEncoder@^2.8.0
		gyverlibs/GyverEncoder
monitor_speed = 115200
