[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_ldf_mode = deep+
board_build.filesystem = littlefs
lib_deps = 
	gyverlibs/GyverDB@^1.4.2
	GyverLibs/Settings@^1.0
	knolleary/PubSubClient@^2.8
	iakop/LiquidCrystal_I2C_ESP32@^1.1.6
	paulstoffregen/Encoder@^1.4.4